"""add_authorized_signature

Revision ID: 0fda0425a04c
Revises: 31d48856caab
Create Date: 2025-12-24 15:03:47.472648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fda0425a04c'
down_revision = '31d48856caab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_purchase_order_signature', 'authorized_signature', ['signature_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_order_signature', type_='foreignkey')
        batch_op.drop_column('signature_id')

    op.drop_table('authorized_signature')
    # ### end Alembic commands ###
