"""Add role_id to Designation

Revision ID: 1d7b2b627b9d
Revises: a101fc8a6234
Create Date: 2025-12-20 11:10:02.897864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7b2b627b9d'
down_revision = 'a101fc8a6234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_designation_role_id', 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_designation_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
