"""Add day counts to Payroll

Revision ID: 229e8105620d
Revises: d0fb18b7ead7
Create Date: 2025-12-21 16:54:24.187087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229e8105620d'
down_revision = 'd0fb18b7ead7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_in_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('arrear_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lopr_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lop_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('lop_days')
        batch_op.drop_column('lopr_days')
        batch_op.drop_column('arrear_days')
        batch_op.drop_column('days_in_month')

    # ### end Alembic commands ###
