"""Add ExpenseClaim model

Revision ID: 2881cefa1b63
Revises: d9c110ac8dbf
Create Date: 2025-12-21 14:14:46.462508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2881cefa1b63'
down_revision = 'd9c110ac8dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('receipt_file', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_claim')
    # ### end Alembic commands ###
