"""Add status to Leave

Revision ID: 30a6c1f07e01
Revises: 1d7b2b627b9d
Create Date: 2025-12-20 13:50:19.649572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a6c1f07e01'
down_revision = '1d7b2b627b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
