"""Add EmployeeDocument model

Revision ID: 53717d4223a1
Revises: 07092ac16870
Create Date: 2025-12-21 14:26:08.234900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53717d4223a1'
down_revision = '07092ac16870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_document')
    # ### end Alembic commands ###
