"""Upgrade Vendor and link to Asset

Revision ID: 6078658a369a
Revises: be32affff173
Create Date: 2025-12-21 16:07:52.779373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6078658a369a'
down_revision = 'be32affff173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_asset_vendor_id', 'vendor', ['vendor_id'], ['id'])

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gstin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_terms', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contract_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('contract_expiry')
        batch_op.drop_column('contract_start')
        batch_op.drop_column('payment_terms')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_account')
        batch_op.drop_column('gstin')
        batch_op.drop_column('category')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_vendor_id', type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
