"""Change reports_to to self-referential FK

Revision ID: 67e07ce4fb74
Revises: 30a6c1f07e01
Create Date: 2025-12-20 14:13:22.778195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e07ce4fb74'
down_revision = '30a6c1f07e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reports_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_employee_profile_reports_to_id', 'employee_profile', ['reports_to_id'], ['id'])
        batch_op.drop_column('reports_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reports_to', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_employee_profile_reports_to_id', type_='foreignkey')
        batch_op.drop_column('reports_to_id')

    # ### end Alembic commands ###
