"""Add is_first_login to User

Revision ID: 70527451dd33
Revises: a6073ac42db1
Create Date: 2025-12-20 22:26:38.786323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70527451dd33'
down_revision = 'a6073ac42db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_login', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_first_login')

    # ### end Alembic commands ###
