"""Add uan_number to EmployeeProfile

Revision ID: 72e80a099028
Revises: 229e8105620d
Create Date: 2025-12-21 17:09:09.263220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e80a099028'
down_revision = '229e8105620d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uan_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.drop_column('uan_number')

    # ### end Alembic commands ###
