"""Update EmployeeProfile and add Designation

Revision ID: 7601ea5c69f9
Revises: 92e21b088695
Create Date: 2025-12-20 09:58:53.476345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7601ea5c69f9'
down_revision = '92e21b088695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pan_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aadhar_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('designation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reports_to', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('previous_employer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_employee_profile_designation_id', 'designation', ['designation_id'], ['id'])
        batch_op.drop_column('designation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_employee_profile_designation_id', type_='foreignkey')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('previous_employer')
        batch_op.drop_column('reports_to')
        batch_op.drop_column('designation_id')
        batch_op.drop_column('branch')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('aadhar_number')
        batch_op.drop_column('pan_number')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('gender')
        batch_op.drop_column('prefix')

    op.drop_table('designation')
    # ### end Alembic commands ###
