"""Leave model use start and end date

Revision ID: 77cf64890ad0
Revises: 67e07ce4fb74
Create Date: 2025-12-20 15:01:24.408274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cf64890ad0'
down_revision = '67e07ce4fb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        # Columns already exist from failed run
        # batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        # batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        pass
    
    # Data Migration: Copy date to start_date and end_date
    op.execute("UPDATE leave SET start_date = date, end_date = date")

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('start_date', nullable=False)
        batch_op.alter_column('end_date', nullable=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
    
    op.execute("UPDATE leave SET date = start_date")

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('date', nullable=False)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
