"""Implement Role Based Access Control

Revision ID: a101fc8a6234
Revises: aa1379b8107b
Create Date: 2025-12-20 10:55:05.535853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a101fc8a6234'
down_revision = 'aa1379b8107b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        
    # Data Migration
    connection = op.get_bind()
    # Insert Default Roles
    connection.execute(sa.text("INSERT INTO role (name, permissions) VALUES ('Admin', 'dashboard,view_employees,add_employee,designations,attendance,roles,change_role,view_assets,add_asset,view_vendors,add_vendor,manage_payroll')"))
    connection.execute(sa.text("INSERT INTO role (name, permissions) VALUES ('Employee', '')"))
    
    # Get Role IDs (Assuming id is auto-increment starting 1, but safer to select)
    # Note: scalar() might return None if execute returns ResultProxy.
    # In newer SQLAlchemy, use result.scalar().
    
    # Migration Logic (Direct SQL for simplicity in Alembic)
    connection.execute(sa.text("UPDATE user SET role_id = (SELECT id FROM role WHERE name='Admin') WHERE role = 'admin'"))
    connection.execute(sa.text("UPDATE user SET role_id = (SELECT id FROM role WHERE name='Employee') WHERE role = 'employee'"))
    connection.execute(sa.text("UPDATE user SET role_id = (SELECT id FROM role WHERE name='Employee') WHERE role_id IS NULL"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role')
        batch_op.create_foreign_key('fk_user_role_id', 'role', ['role_id'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint('fk_user_role_id', type_='foreignkey')
        batch_op.create_index('ix_user_role', ['role'], unique=False)
        batch_op.drop_column('role_id')

    op.drop_table('role')
    # ### end Alembic commands ###
