"""add_tax_percentage_to_po

Revision ID: a56f81c3d50a
Revises: 0fda0425a04c
Create Date: 2025-12-24 17:59:13.972031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56f81c3d50a'
down_revision = '0fda0425a04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('tax_percentage')

    # ### end Alembic commands ###
