"""Add resigned fields to EmployeeProfile

Revision ID: a6073ac42db1
Revises: 77cf64890ad0
Create Date: 2025-12-20 17:29:02.323346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6073ac42db1'
down_revision = '77cf64890ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resigned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resigned_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.drop_column('resigned_date')
        batch_op.drop_column('is_resigned')

    # ### end Alembic commands ###
