"""Add PF and ESI numbers

Revision ID: ac04de1ded66
Revises: 72e80a099028
Create Date: 2025-12-21 17:19:24.784039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac04de1ded66'
down_revision = '72e80a099028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pf_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('esi_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.drop_column('esi_number')
        batch_op.drop_column('pf_number')

    # ### end Alembic commands ###
