"""Advanced Payroll Models

Revision ID: b3e6f9a84b49
Revises: 6078658a369a
Create Date: 2025-12-21 16:21:57.855361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e6f9a84b49'
down_revision = '6078658a369a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('monthly_ctc', sa.Float(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=True),
    sa.Column('hra', sa.Float(), nullable=True),
    sa.Column('conveyance', sa.Float(), nullable=True),
    sa.Column('medical', sa.Float(), nullable=True),
    sa.Column('special_allowance', sa.Float(), nullable=True),
    sa.Column('pf', sa.Float(), nullable=True),
    sa.Column('esi', sa.Float(), nullable=True),
    sa.Column('professional_tax', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('conveyance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('medical', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('special_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reimbursements', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('esi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('professional_tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tds', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lop', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_deductions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pay_period_start',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('pay_period_end',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('deductions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deductions', sa.FLOAT(), nullable=True))
        batch_op.alter_column('pay_period_end',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('pay_period_start',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('total_deductions')
        batch_op.drop_column('lop')
        batch_op.drop_column('tds')
        batch_op.drop_column('professional_tax')
        batch_op.drop_column('esi')
        batch_op.drop_column('pf')
        batch_op.drop_column('reimbursements')
        batch_op.drop_column('bonus')
        batch_op.drop_column('special_allowance')
        batch_op.drop_column('medical')
        batch_op.drop_column('conveyance')
        batch_op.drop_column('hra')
        batch_op.drop_column('basic')

    op.drop_table('salary_structure')
    # ### end Alembic commands ###
