"""Upgrade Asset and add AssetHistory

Revision ID: be32affff173
Revises: 53717d4223a1
Create Date: 2025-12-21 15:51:04.786637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be32affff173'
down_revision = '53717d4223a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('model_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('purchase_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('warranty_expiry', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('warranty_expiry')
        batch_op.drop_column('purchase_cost')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('condition')
        batch_op.drop_column('category')
        batch_op.drop_column('model_name')
        batch_op.drop_column('brand')

    op.drop_table('asset_history')
    # ### end Alembic commands ###
