"""Add incentives to Payroll

Revision ID: d0fb18b7ead7
Revises: b3e6f9a84b49
Create Date: 2025-12-21 16:27:07.344408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fb18b7ead7'
down_revision = 'b3e6f9a84b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incentives', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('incentives')

    # ### end Alembic commands ###
