"""Add Appraisal model

Revision ID: d9c110ac8dbf
Revises: 95a56ed13724
Create Date: 2025-12-21 13:46:12.770655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c110ac8dbf'
down_revision = '95a56ed13724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('appraisal_date', sa.Date(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employee_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appraisal')
    # ### end Alembic commands ###
